Update draft-ietf-rats-architecture.md
ietf-rats-wg/architecture pull request #152
Opened 2020-09-22 21:11 UTC by nedmsmith

Suggested new text for Endorsements definition to make it slightly more broad, but constrained to the operations of an Attesting Environment (which is a subset of an Attester that also might contain Target Environments and other environments) which is focus for why a Verifier cares to get Endorsements.

2020-09-22 23:30 UTC, mcr approved these changes

2020-09-24 19:34 UTC, laurencelundblade commented on draft-ietf-rats-architecture.md
> +: A secure statement that some entity (typically a manufacturer) vouches for the integrity of an Attesting Environment's various capabilities such as Claims collection and Evidence signing
s/some entity/an Endorser/

2020-09-25 09:42 UTC, William-PanWei approved these changes

2020-09-25 13:40 UTC, henkbirkholz requested changes
This now aligns excellently with the overall terminology.

Unfortunately, this now uses a term that is well-defined in section 4.2., but not included in the "upfront" terminology section. This is fine text! But it might now impliy the addition of Attesting Environment into this section.

2020-09-25 14:17 UTC, mcr approved these changes

2020-09-25 14:17 UTC, mcr commented on draft-ietf-rats-architecture.md
> +: A secure statement that some entity (typically a manufacturer) vouches for the integrity of an Attesting Environment's various capabilities such as Claims collection and Evidence signing
```suggestion
: A secure statement that an Endorser vouches for the integrity of an Attesting Environment's various capabilities such as Claims collection and Evidence signing
```

2020-09-25 14:18 UTC, mcr approved these changes

2020-09-25 14:18 UTC, mcr commented on draft-ietf-rats-architecture.md
> +: A secure statement that an Endorser vouches for the integrity of an Attesting Environment's various capabilities such as Claims collection and Evidence signing
```suggestion
: A secure statement that an Endorser vouches for the integrity of an Attester's various capabilities such as Claims collection and Evidence signing
```

2020-09-25 14:19 UTC, merged