Terminology rework 2
ietf-rats-wg/architecture pull request #202
Opened 2020-12-01 17:06 UTC by mcr

This reworks the pull request: #164 using the latest text.
Commit 1 - move all the text.
Commit 2 - add produces/consumes.
Commit 3 - move the text into categories.

Reviewing the commits individually is probably better.

2020-12-01 17:07 UTC, mcr commented
Please review @SimonFrost-Arm

2020-12-01 17:56 UTC, SimonFrost-Arm approved these changes

2020-12-08 14:48 UTC, dthaler requested changes

2020-12-08 14:48 UTC, dthaler commented on draft-ietf-rats-architecture.md
> +Negotiates: the relationship between an Attester and a Verifier.
No idea what this means
```suggestion
```

2020-12-08 14:48 UTC, dthaler commented on draft-ietf-rats-architecture.md
> +: A role performed by an entity that depends on the validity of information about an Attester, for purposes of reliably applying application specific actions.  Compare /relying party/ in {{RFC4949}}
```suggestion
: A role performed by an entity that depends on the validity of information about an Attester, for purposes of reliably applying application specific actions.  Compare /relying party/ in {{RFC4949}}.
```
If we put punctuation at end of other definitions, be consistent here too.

2020-12-08 14:48 UTC, dthaler commented on draft-ietf-rats-architecture.md
> +(Compare /claim/ in {{RFC7519}})
```suggestion
Compare /claim/ in {{RFC7519}}.
```
Use punctuation consistently between here, line 519, and line 571

2020-12-08 14:48 UTC, dthaler commented on draft-ietf-rats-architecture.md
> +Endorsement:
This definition should move up to line 580

2020-12-08 14:48 UTC, dthaler commented on draft-ietf-rats-architecture.md
```suggestion
Used By: Verifier;
Produced By: Endorser
```

2020-12-08 14:48 UTC, dthaler commented on draft-ietf-rats-architecture.md
>  Verifier:
This is already up at line 523

2020-12-08 15:11 UTC, merged