Rework Layered Attestation Environments intro
ietf-rats-wg/architecture pull request #256
Opened 2021-01-21 09:42 UTC by thomas-fossati

Based on Henk's proposal and Dave's comments.

Fixes #230

2021-01-21 15:02 UTC, mcr requested changes
I prefer that each sentence start on a newline as it makes git diffs easier.

2021-01-22 08:51 UTC, thomas-fossati commented
> I prefer that each sentence start on a newline as it makes git diffs easier.

@mcr : This is a complete re-write of the paragraph which needs to be read in its entirety.  I'm not sure whether a line-by-line diff is of any help?  

That said, if you really want I could do that easily.

2021-01-22 10:19 UTC, henkbirkholz commented on draft-ietf-rats-architecture.md
> +The root layers of an Attester are called roots of trust.
```suggestion
The root layer of an Attester encompasses the initial roots of trust included in an Attester
```

2021-01-22 10:30 UTC, henkbirkholz commented on draft-ietf-rats-architecture.md
> +In order to appraise Evidence produced by an Attester, the Verifier needs to trust the Attester's root of trust.
```suggestion
In order to appraise Evidence generated by an Attester, the Verifier needs to trust the Attester's root of trust.
```

2021-01-22 10:44 UTC, henkbirkholz commented on draft-ietf-rats-architecture.md
> +Claims can be collected from or about each layer, including roots of trust.
"Claims can be collected from or about each layer, including roots of trust."

This is technically correct. On the glossary level we have the responsibility to make absolutely sure that the reader is aware that a root of trust cannot ever generate Evidence from Claims about itself.

2021-01-22 16:27 UTC, mcr commented
Thomas Fossati <notifications@github.com> wrote:
    > @mcr : This is a complete re-write of the paragraph which needs to be
    > read in its entirety.  I'm not sure whether a line-by-line diff is of
    > any help?

It helps with the next edit that comes along.

2021-01-22 18:28 UTC, thomas-fossati commented
> Thomas Fossati <notifications@github.com> wrote: @mcr : This is a complete re-write of the paragraph which needs to be read in its entirety. I'm not sure whether a line-by-line diff is of any help? It helps with the next edit that comes along.

OK, done!

2021-01-23 00:37 UTC, mcr approved these changes

2021-01-24 20:39 UTC, nedmsmith approved these changes

2021-01-24 20:47 UTC, nedmsmith requested changes

2021-01-24 20:47 UTC, nedmsmith commented on draft-ietf-rats-architecture.md
Normally, claims are not self-asserted by a layer or root of trust.

2021-01-26 02:37 UTC, dthaler approved these changes

2021-01-26 15:28 UTC, mcr commented on draft-ietf-rats-architecture.md
> +Claims can be collected from or about each layer, including roots of trust.
```suggestion
Claims can be collected from or about each layer.
```

2021-01-26 15:32 UTC, merged