Why is this work important?
ietf-rats-wg/architecture pull request #318
Opened 2021-03-16 16:00 UTC by elear

Here's a strawman intro that explains the import of the work in a concrete manner.

Fixes #314

2021-03-17 11:31 UTC, henkbirkholz commented
While I can see the use of the additional content, I thought you intended to improve the introduction. Do you really intended to start an abstract text with a question? I am not sure how people who actually use a CMS would react to that.

2021-03-23 13:56 UTC, mcr commented on draft-ietf-rats-architecture.md
> +   were shared only among systems that were trustworthy?
Second person is great, but are we doing it?

2021-03-23 14:11 UTC, dthaler commented on draft-ietf-rats-architecture.md
> +This is the goal of the Remote Attestation architecture (RATS).
RATS is the acronym for Remote Attestation ProcedureS

2021-03-23 14:12 UTC, mcr requested changes

2021-03-23 14:12 UTC, mcr commented on draft-ietf-rats-architecture.md
>  --- abstract
This belongs in the intro.

2021-03-30 00:34 UTC, mcr approved these changes

2021-03-30 01:06 UTC, dthaler approved these changes
Ok, but see suggested wording improvements

2021-03-30 01:06 UTC, dthaler commented on draft-ietf-rats-architecture.md
> +In network protocol exchanges it is useful for one end of a
```suggestion
In network protocol exchanges it is often useful for one end of a
```

2021-03-30 01:06 UTC, dthaler commented on draft-ietf-rats-architecture.md
> +communication to know if the other end is in a proper operating state.
```suggestion
communication to know whether the other end is in a proper operating state.
```
(https://grammarist.com/grammar/if-vs-whether/ says "if" is considered informal, though the meaning is the same, so to me "whether" reads better)

2021-03-30 01:06 UTC, dthaler commented on draft-ietf-rats-architecture.md
> +How should one system know that another system can be trusted?  This
```suggestion
How can one system know that another system can be trusted?  This
```

2021-03-30 14:33 UTC, mcr commented on draft-ietf-rats-architecture.md
> +communication to know if the other end is in a proper operating state.
```suggestion
communication to know if the other end is in an intended operating state.
```

2021-03-30 14:34 UTC, mcr commented on draft-ietf-rats-architecture.md
> +communication to know whether the other end is in a proper operating state.
```suggestion
communication to know whether the other end is in an intended operating state.
```

2021-03-30 14:35 UTC, mcr commented on draft-ietf-rats-architecture.md
> +This memo provides an architectural overview of the entities involved
```suggestion
This document provides an architectural overview of the entities involved
```

2021-03-30 14:46 UTC, mcr commented on draft-ietf-rats-architecture.md
> +trusted computing elements are maturing in processor architectures.
```suggestion
The question of how one system can know that another system can be trusted has found new interest and relevance in a world where trusted computing elements are maturing in processor architectures.
```

2021-03-30 16:19 UTC, mcr commented
Closed with commit:d7227b2

2021-03-30 16:19 UTC, closed without merging