sequence diagrams render as SVG in HTML
ietf-rats-wg/architecture pull request #419
Opened 2022-06-13 14:33 UTC by thomas-fossati

Same as #418 but for sequence diagrams (as per popular demand)

2022-06-13 15:01 UTC, henkbirkholz requested changes
minor optics

2022-06-13 15:39 UTC, nedmsmith approved these changes

2022-06-13 17:05 UTC, mcr approved these changes

2022-06-13 17:07 UTC, mcr commented on draft-ietf-rats-architecture.md
> +     time(IR'_a)<-----I'-o--I'-----> time(IR'_v) --> time(IR'_r)
I noticed the strange circle symbol in the SVG here, and I don't know what it means.

2022-06-13 18:00 UTC, thomas-fossati commented on draft-ietf-rats-architecture.md
> +     time(IR'_a)<-----I'-o--I'-----> time(IR'_v) --> time(IR'_r)
With the original '+' the horizontal line just passes through the vertical axis.  But the thing that (I think) needs to be shown here is the broadcast origin, which I pictorially made into a circle.  Like a lightbulb, or a tiny sun if you want.

2022-06-13 18:00 UTC, thomas-fossati commented on draft-ietf-rats-architecture.md
> +        |                 time(RA_r)<--Attestation Result------+
Fixed in 246620c

2022-06-13 18:01 UTC, thomas-fossati commented on draft-ietf-rats-architecture.md
> +     |                    time(RA_r)<--Attestation Result--+
Fixed in 246620c

2022-06-13 18:01 UTC, thomas-fossati commented on draft-ietf-rats-architecture.md
> +     time(IR'_a)<-----I'-o--I'-----> time(IR'_v) --> time(IR'_r)
This one to was fixed in 246620c

2022-06-13 19:09 UTC, mcr commented on draft-ietf-rats-architecture.md
> +     time(IR'_a)<-----I'-o--I'-----> time(IR'_v) --> time(IR'_r)
I think that it's really the ~ that introduces visual disconnects that prevents understanding here.
I don't feel strongly though, so I've already marked approve. 
I await comments from @dthaler

2022-06-13 19:10 UTC, mcr commented on draft-ietf-rats-architecture.md
>          ~                ~                ~               ~
```suggestion
        ~                |                ~               ~
```

2022-06-13 19:12 UTC, mcr commented on draft-ietf-rats-architecture.md
>          ~                ~                ~               ~
Don't continue the Epoch line

2022-06-13 19:16 UTC, mcr commented on draft-ietf-rats-architecture.md
> +     time(IR'_a) <----I'-o--I'-----> time(IR'_v) --> time(IR'_r)
In the rendering that I'm seeing on my desktop, I see: 
  http://www.sandelman.ca/tmp/mcrcapture/2940.2022-06-13/capture1.png
note how I' to the left, but not I' to the right.  Bug in aasvg?

2022-06-13 19:16 UTC, mcr commented on draft-ietf-rats-architecture.md
> +     time(IR'_a) <----I'-o--I'-----> time(IR'_v) --> time(IR'_r)
```suggestion
     time(IR'_a) <----I'-o--I' ----> time(IR'_v) --> time(IR'_r)
```

2022-06-14 04:00 UTC, William-PanWei approved these changes

2022-06-14 12:33 UTC, merged